apiVersion: apps/v1
kind: Deployment
metadata:
  name: mir-test
  labels:
    app: mir-test
spec:
  replicas: 1 # Keep only 1 pod for lowest cost
  selector:
    matchLabels:
      app: mir-test
  template:
    metadata:
      labels:
        app: mir-test
    spec:
      containers:
      - name: mir-test
        image: europe-west3-docker.pkg.dev/testproject-464712/mir-test-repo/mir-test:latest
        imagePullPolicy: Always # Always pull latest image since we have a simple (bad) cicd, we should think about rollout strategy too
        ports:
        - containerPort: 8000 # default fastapi
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-url-secret
              key: DATABASE_URL
