name: CI/CD GKE Deployment

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: pytest app/tests/

    #TBD
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: testproject-464712
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # The building process should be handled better with dynamic tags etc but lets keep it simple
    - name: Docker auth
      run: echo "$GCP_SA_KEY" > ./google-credentials.json && gcloud auth login --brief --cred-file=./google-credentials.json --update-adc gcloud auth configure-docker --quiet

    - name: Build image
      run: docker build -t europe-west3-docker.pkg.dev/testproject-464712/mir-test-repo/mir-test:$GITHUB_SHA .

    - name: Push image
      run: docker push europe-west3-docker.pkg.dev/testproject-464712/mir-test-repo/mir-test:$GITHUB_SHA

    - name: Get creds
      run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone europe-west3-a

    - name: Create secret
      run: |
        kubectl create secret generic db-url-secret \
          --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy
      run: |
        kubectl set image deployment/mir-test mir-test=europe-west3-docker.pkg.dev/testproject-464712/mir-test-repo/mir-test:$GITHUB_SHA
        kubectl rollout status deployment/mir-test
