name: CI/CD GKE Deployment

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: pytest app/tests/

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        # Project ID hardcoded for simplicity, but better to keep dynamic
        project_id: testproject-464712
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Docker auth
      run: gcloud auth configure-docker

    - name: Build image
      run: docker build -t gcr.io/testproject-464712/mir-test:$GITHUB_SHA .

    - name: Push image
      run: docker push gcr.io/testproject-464712/mir-test:$GITHUB_SHA

    - name: Get creds
      run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone europe-west3-a

    - name: Create secret
      run: |
        kubectl create secret generic db-url-secret \
          --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy
      run: |
        kubectl set image deployment/mir-test mir-test=gcr.io/testproject-464712/mir-test:$GITHUB_SHA
        kubectl rollout status deployment/mir-test
